# примеры API-запросов

@baseUrl = http://localhost:8000/api
@token1 = f09463281d5c91d8a22f3bd187e80fa047241e8f
@token2 = 999d5249e7638b2605466b8586cea7e6fe0e42f6

@token3 = 48ee1a79deaa0eb2b9e0fb2f5861ba5494c70a32

# получение объявлений
GET {{baseUrl}}/advertisements/
Content-Type: application/json

###

# создание объявления
POST {{baseUrl}}/advertisements/
Content-Type: application/json
Authorization: Token {{token3}}

{
  "title": "Шкаф IKEA4",
  "description": "Срочно"
}

###

# попытка поменять объявление
PATCH {{baseUrl}}/advertisements/27/
Content-Type: application/json
Authorization: Token {{token3}}

{
  "status": "CLOSED"
}

###

# попытка удалить объявление
DELETE {{baseUrl}}/advertisements/25/
Content-Type: application/json
Authorization: Token {{token3}}

###

# фильтрация по создателю
GET {{baseUrl}}/advertisements/?creator=3
Content-Type: application/json

###

# фильтрация по статусу
GET {{baseUrl}}/advertisements/?status=OPEN&creator=3
Content-Type: application/json.

###

# фильтрация по статусу
GET {{baseUrl}}/advertisements/?status=CLOSED
Content-Type: application/json.

###

# фильтрация по дате
GET {{baseUrl}}/advertisements/?created_at_before=2021-09-04
Content-Type: application/json

###

# фильтрация по дате
GET {{baseUrl}}/advertisements/?created_at_after=2021-09-04
Content-Type: application/json
