# Generated by Django 3.1.2 on 2021-09-09 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('price', models.IntegerField()),
                ('image', models.TextField()),
                ('release_date', models.DateTimeField(default=None)),
                ('lte_exists', models.BooleanField(default=True)),
                ('slug', models.CharField(max_length=50)),
            ],
        ),
    ]
